kumuluzee:
  name: merchants-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/MerchantsDS
      connection-url: jdbc:postgresql://localhost:5432/merchants
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/MerchantsDS
  metrics:
    web-instrumentation:
      - name: merchants-endpoint
        url-pattern: /v1/merchants/*
rest-properties:
  maintenance-mode: false
